from distutils.core import setup, Extension
from numpy import get_include

mvnpdf_extension = Extension('fcm.statistics._mvnpdf',
                             sources = ['src/statistics/%s' % i for i in 
                                ['mvnpdf_ext/mvnpdf.cpp',
                                'mvnpdf_ext/mvnpdf_wrap.cpp',
                                'cdp_ext/random/specialfunctions2.cpp',
                                'cdp_ext/random/SpecialFunctions.cpp',
                                'cdp_ext/matrix/newmat1.cpp',
                                'cdp_ext/matrix/newmat2.cpp',
                                'cdp_ext/matrix/newmat3.cpp',
                                'cdp_ext/matrix/newmat4.cpp',
                                'cdp_ext/matrix/newmat5.cpp',
                                'cdp_ext/matrix/newmat6.cpp',
                                'cdp_ext/matrix/newmat7.cpp',
                                'cdp_ext/matrix/newmat8.cpp',
                                'cdp_ext/matrix/newmat9.cpp',
                                'cdp_ext/matrix/newmatex.cpp',
                                'cdp_ext/matrix/myexcept.cpp',
                                'cdp_ext/matrix/bandmat.cpp',
                                'cdp_ext/matrix/submat.cpp',
                                'cdp_ext/matrix/newmatrm.cpp',
                                'cdp_ext/matrix/svd.cpp',
                                'cdp_ext/matrix/sort.cpp',
                                'cdp_ext/matrix/cholesky.cpp']],
                            include_dirs = [get_include(), 
                                    'src/statistics/cdp_ext/matrix',
                                    'src/statistics/cdp_ext/random',
                                    'src/statistics/mvnpdf_ext'],
                            #libraries = ['m', 'stdc++']
                            )
                                        

logicle_extension = Extension('fcm.core._logicle',
                              sources = [ 'src/core/logicle_ext/%s' %i for i in [
                                'Logicle.cpp',
                                'my_logicle.cpp',
                                'my_logicle_wrapper.cpp']],
                              include_dirs = [get_include()]
                              )
cdp_extension = Extension('fcm.statistics._cdp',
                          sources = [ 'src/statistics/cdp_ext/%s' %i for i in ['cdp/Model.cpp',
                                'cdp/cdpp.cpp',
                                'cdp/cdp_em.cpp',
                                'cdp/cdp.cpp',
                                'cdp/cdp2.cpp',
                                'cdp/cdp4.cpp',
                                'cdp/cdpresult.cpp',
                                'cdp/cdpprior.cpp',
                                'cdp/cdpresultem.cpp',
                                'cdp/cdpbase.cpp',
                                'wrapper/cdpcluster.cpp',
                                'wrapper/cdpemcluster.cpp',
                                'wrapper/cdpcluster_wrap.cpp',
                                'random/specialfunctions2.cpp',
                                'random/SpecialFunctions.cpp',
                                'matrix/sort.cpp',
                                'matrix/newmat9.cpp',
                                'matrix/newmatrm.cpp',
                                'matrix/newmat7.cpp',
                                'matrix/myexcept.cpp',
                                'matrix/newmatnl.cpp',
                                'matrix/jacobi.cpp',
                                'matrix/newmat6.cpp',
                                'matrix/newmat1.cpp',
                                'matrix/bandmat.cpp',
                                'matrix/svd.cpp',
                                'matrix/newmat8.cpp',
                                'matrix/cholesky.cpp',
                                'matrix/submat.cpp',
                                'matrix/hholder.cpp',
                                'matrix/fft.cpp',
                                'matrix/evalue.cpp',
                                'matrix/newmat2.cpp',
                                'matrix/newmat5.cpp',
                                'matrix/newmatex.cpp',
                                'matrix/newfft.cpp',
                                'matrix/newmat4.cpp',
                                'matrix/newmat3.cpp',
                                'munkres/Munkres.cpp']],
                                
                            include_dirs = [get_include(), 
                                'src/statistics/cdp_ext/matrix', 
                                'src/statistics/cdp_ext/random', 
                                'src/statistics/cdp_ext/cdp', 
                                'src/statistics/cdp_ext/wrapper',
                                'src/statistics/cdp_ext/munkres'],
                            #libraries = ['m', 'stdc++'],
                            define_macros = [('PYWRAP', 1)]
                            )

setup(name='fcm',
      version='0.7',
      packages=['fcm', 'fcm.core', 'fcm.graphics', 'fcm.gui', 'fcm.io', 'fcm.statistics' ],
      package_dir = {'fcm': 'src'},
      package_data= {'': ['data/*']},
      description='Python Flow Cytometry (FCM) Tools',
      author='Jacob Frelinger',
      author_email='jacob.frelinger@duke.edu',
      ext_modules = [cdp_extension, logicle_extension, mvnpdf_extension],
      requires=['numpy (>=1.3.0)',
                'scipy (>=0.6)',
                'enthought.traits (>=3.1)'], # figure out the rest of what's a required package.
      )
