# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.39
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_cdpfoo', [dirname(__file__)])
        except ImportError:
            import _cdpfoo
            return _cdpfoo
        if fp is not None:
            try:
                _mod = imp.load_module('_cdpfoo', fp, pathname, description)
            finally:
                fp.close()
                return _mod
    _cdpfoo = swig_import_helper()
    del swig_import_helper
else:
    import _cdpfoo
del version_info
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

class cdpcluster:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, cdpcluster, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, cdpcluster, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _cdpfoo.new_cdpcluster(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _cdpfoo.delete_cdpcluster
    __del__ = lambda self : None;
    def run(self): return _cdpfoo.cdpcluster_run(self)
    def step(self): return _cdpfoo.cdpcluster_step(self)
    def stepburn(self): return _cdpfoo.cdpcluster_stepburn(self)
    def setT(self, *args): return _cdpfoo.cdpcluster_setT(self, *args)
    def setJ(self, *args): return _cdpfoo.cdpcluster_setJ(self, *args)
    def setBurnin(self, *args): return _cdpfoo.cdpcluster_setBurnin(self, *args)
    def setIter(self, *args): return _cdpfoo.cdpcluster_setIter(self, *args)
    def setVerbose(self, *args): return _cdpfoo.cdpcluster_setVerbose(self, *args)
    def getBurnin(self): return _cdpfoo.cdpcluster_getBurnin(self)
    def getIter(self): return _cdpfoo.cdpcluster_getIter(self)
    def getn(self): return _cdpfoo.cdpcluster_getn(self)
    def getd(self): return _cdpfoo.cdpcluster_getd(self)
    def getclustN(self): return _cdpfoo.cdpcluster_getclustN(self)
    def getT(self): return _cdpfoo.cdpcluster_getT(self)
    def getJ(self): return _cdpfoo.cdpcluster_getJ(self)
    def setlambda0(self, *args): return _cdpfoo.cdpcluster_setlambda0(self, *args)
    def getlambda0(self): return _cdpfoo.cdpcluster_getlambda0(self)
    def setphi0(self, *args): return _cdpfoo.cdpcluster_setphi0(self, *args)
    def getphi0(self): return _cdpfoo.cdpcluster_getphi0(self)
    def setnu0(self, *args): return _cdpfoo.cdpcluster_setnu0(self, *args)
    def getnu0(self): return _cdpfoo.cdpcluster_getnu0(self)
    def setgamma(self, *args): return _cdpfoo.cdpcluster_setgamma(self, *args)
    def getgamma(self): return _cdpfoo.cdpcluster_getgamma(self)
    def setnu(self, *args): return _cdpfoo.cdpcluster_setnu(self, *args)
    def getnu(self): return _cdpfoo.cdpcluster_getnu(self)
    def sete0(self, *args): return _cdpfoo.cdpcluster_sete0(self, *args)
    def gete0(self): return _cdpfoo.cdpcluster_gete0(self)
    def setf0(self, *args): return _cdpfoo.cdpcluster_setf0(self, *args)
    def getf0(self): return _cdpfoo.cdpcluster_getf0(self)
    def setee(self, *args): return _cdpfoo.cdpcluster_setee(self, *args)
    def getee(self): return _cdpfoo.cdpcluster_getee(self)
    def setff(self, *args): return _cdpfoo.cdpcluster_setff(self, *args)
    def getff(self): return _cdpfoo.cdpcluster_getff(self)
    def getMu(self, *args): return _cdpfoo.cdpcluster_getMu(self, *args)
    def getSigma(self, *args): return _cdpfoo.cdpcluster_getSigma(self, *args)
    def getp(self, *args): return _cdpfoo.cdpcluster_getp(self, *args)
cdpcluster_swigregister = _cdpfoo.cdpcluster_swigregister
cdpcluster_swigregister(cdpcluster)



